/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ADDRESSLANG {
    EN = 'EN',
    TH = 'TH'
}

export function ADDRESSLANGFromJSON(json: any): ADDRESSLANG {
    return ADDRESSLANGFromJSONTyped(json, false);
}

export function ADDRESSLANGFromJSONTyped(json: any, ignoreDiscriminator: boolean): ADDRESSLANG {
    return json as ADDRESSLANG;
}

export function ADDRESSLANGToJSON(value?: ADDRESSLANG | null): any {
    return value as any;
}

