/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IAddress,
    IAddressFromJSON,
    IAddressFromJSONTyped,
    IAddressToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddressAddReq
 */
export interface AddressAddReq {
    /**
     * 
     * @type {number}
     * @memberof AddressAddReq
     */
    userId: number;
    /**
     * 
     * @type {Array<IAddress>}
     * @memberof AddressAddReq
     */
    addresses: Array<IAddress>;
}

export function AddressAddReqFromJSON(json: any): AddressAddReq {
    return AddressAddReqFromJSONTyped(json, false);
}

export function AddressAddReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressAddReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'addresses': ((json['addresses'] as Array<any>).map(IAddressFromJSON)),
    };
}

export function AddressAddReqToJSON(value?: AddressAddReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'addresses': ((value.addresses as Array<any>).map(IAddressToJSON)),
    };
}


