/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IAddress,
    IAddressFromJSON,
    IAddressFromJSONTyped,
    IAddressToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddressUpdateReq
 */
export interface AddressUpdateReq {
    /**
     * 
     * @type {IAddress}
     * @memberof AddressUpdateReq
     */
    address: IAddress;
}

export function AddressUpdateReqFromJSON(json: any): AddressUpdateReq {
    return AddressUpdateReqFromJSONTyped(json, false);
}

export function AddressUpdateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressUpdateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': IAddressFromJSON(json['address']),
    };
}

export function AddressUpdateReqToJSON(value?: AddressUpdateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': IAddressToJSON(value.address),
    };
}


