/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressRemoveReq
 */
export interface AddressRemoveReq {
    /**
     * 
     * @type {number}
     * @memberof AddressRemoveReq
     */
    userId: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddressRemoveReq
     */
    addressIds: Array<string>;
}

export function AddressRemoveReqFromJSON(json: any): AddressRemoveReq {
    return AddressRemoveReqFromJSONTyped(json, false);
}

export function AddressRemoveReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressRemoveReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'addressIds': json['addressIds'],
    };
}

export function AddressRemoveReqToJSON(value?: AddressRemoveReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'addressIds': value.addressIds,
    };
}


