/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AMOUNTTYPE {
    PERCENTAGE = 'PERCENTAGE',
    FLAT = 'FLAT'
}

export function AMOUNTTYPEFromJSON(json: any): AMOUNTTYPE {
    return AMOUNTTYPEFromJSONTyped(json, false);
}

export function AMOUNTTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): AMOUNTTYPE {
    return json as AMOUNTTYPE;
}

export function AMOUNTTYPEToJSON(value?: AMOUNTTYPE | null): any {
    return value as any;
}

