/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelOrderReq
 */
export interface CancelOrderReq {
    /**
     * 
     * @type {string}
     * @memberof CancelOrderReq
     */
    cancelReason?: string;
}

export function CancelOrderReqFromJSON(json: any): CancelOrderReq {
    return CancelOrderReqFromJSONTyped(json, false);
}

export function CancelOrderReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelOrderReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cancelReason': !exists(json, 'cancelReason') ? undefined : json['cancelReason'],
    };
}

export function CancelOrderReqToJSON(value?: CancelOrderReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cancelReason': value.cancelReason,
    };
}


