/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CLOTHESIZE {
    FREESIZE = 'FREE_SIZE',
    MINI = 'MINI',
    XS = 'XS',
    S = 'S',
    M = 'M',
    L = 'L',
    XL = 'XL',
    XXL = 'XXL'
}

export function CLOTHESIZEFromJSON(json: any): CLOTHESIZE {
    return CLOTHESIZEFromJSONTyped(json, false);
}

export function CLOTHESIZEFromJSONTyped(json: any, ignoreDiscriminator: boolean): CLOTHESIZE {
    return json as CLOTHESIZE;
}

export function CLOTHESIZEToJSON(value?: CLOTHESIZE | null): any {
    return value as any;
}

