/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TAXTYPE,
    TAXTYPEFromJSON,
    TAXTYPEFromJSONTyped,
    TAXTYPEToJSON,
} from './';

/**
 * 
 * @export
 * @interface ColorUpdateReq
 */
export interface ColorUpdateReq {
    /**
     * 
     * @type {number}
     * @memberof ColorUpdateReq
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ColorUpdateReq
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ColorUpdateReq
     */
    titleTh?: string;
    /**
     * 
     * @type {TAXTYPE}
     * @memberof ColorUpdateReq
     */
    taxType: TAXTYPE;
    /**
     * 
     * @type {boolean}
     * @memberof ColorUpdateReq
     */
    isActive: boolean;
    /**
     * 
     * @type {any}
     * @memberof ColorUpdateReq
     */
    taxPrimaryImgId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ColorUpdateReq
     */
    taxThumbnailId?: any | null;
    /**
     * 
     * @type {number}
     * @memberof ColorUpdateReq
     */
    relatedProductsId?: number;
    /**
     * 
     * @type {number}
     * @memberof ColorUpdateReq
     */
    productId: number;
}

export function ColorUpdateReqFromJSON(json: any): ColorUpdateReq {
    return ColorUpdateReqFromJSONTyped(json, false);
}

export function ColorUpdateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorUpdateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'titleTh': !exists(json, 'title_th') ? undefined : json['title_th'],
        'taxType': TAXTYPEFromJSON(json['tax_type']),
        'isActive': json['isActive'],
        'taxPrimaryImgId': !exists(json, 'TaxPrimaryImgId') ? undefined : json['TaxPrimaryImgId'],
        'taxThumbnailId': !exists(json, 'TaxThumbnailId') ? undefined : json['TaxThumbnailId'],
        'relatedProductsId': !exists(json, 'relatedProductsId') ? undefined : json['relatedProductsId'],
        'productId': json['productId'],
    };
}

export function ColorUpdateReqToJSON(value?: ColorUpdateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'title_th': value.titleTh,
        'tax_type': TAXTYPEToJSON(value.taxType),
        'isActive': value.isActive,
        'TaxPrimaryImgId': value.taxPrimaryImgId,
        'TaxThumbnailId': value.taxThumbnailId,
        'relatedProductsId': value.relatedProductsId,
        'productId': value.productId,
    };
}


