/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContentPayload,
    ContentPayloadFromJSON,
    ContentPayloadFromJSONTyped,
    ContentPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface ContentResponse
 */
export interface ContentResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ContentResponse
     */
    success: boolean;
    /**
     * 
     * @type {ContentPayload}
     * @memberof ContentResponse
     */
    payload?: ContentPayload;
    /**
     * 
     * @type {any}
     * @memberof ContentResponse
     */
    message?: any | null;
}

export function ContentResponseFromJSON(json: any): ContentResponse {
    return ContentResponseFromJSONTyped(json, false);
}

export function ContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'payload': !exists(json, 'payload') ? undefined : ContentPayloadFromJSON(json['payload']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ContentResponseToJSON(value?: ContentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'payload': ContentPayloadToJSON(value.payload),
        'message': value.message,
    };
}


