/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CONTENTTYPE {
    TEXT = 'TEXT',
    LINK = 'LINK'
}

export function CONTENTTYPEFromJSON(json: any): CONTENTTYPE {
    return CONTENTTYPEFromJSONTyped(json, false);
}

export function CONTENTTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): CONTENTTYPE {
    return json as CONTENTTYPE;
}

export function CONTENTTYPEToJSON(value?: CONTENTTYPE | null): any {
    return value as any;
}

