/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IContent,
    IContentFromJSON,
    IContentFromJSONTyped,
    IContentToJSON,
} from './';

/**
 * 
 * @export
 * @interface ContentPayload
 */
export interface ContentPayload {
    /**
     * 
     * @type {IContent}
     * @memberof ContentPayload
     */
    content?: IContent;
    /**
     * 
     * @type {Array<IContent>}
     * @memberof ContentPayload
     */
    contents?: Array<IContent>;
    /**
     * 
     * @type {number}
     * @memberof ContentPayload
     */
    listLength?: number;
}

export function ContentPayloadFromJSON(json: any): ContentPayload {
    return ContentPayloadFromJSONTyped(json, false);
}

export function ContentPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : IContentFromJSON(json['content']),
        'contents': !exists(json, 'contents') ? undefined : ((json['contents'] as Array<any>).map(IContentFromJSON)),
        'listLength': !exists(json, 'listLength') ? undefined : json['listLength'],
    };
}

export function ContentPayloadToJSON(value?: ContentPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': IContentToJSON(value.content),
        'contents': value.contents === undefined ? undefined : ((value.contents as Array<any>).map(IContentToJSON)),
        'listLength': value.listLength,
    };
}


