/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CurrencyPayload,
    CurrencyPayloadFromJSON,
    CurrencyPayloadFromJSONTyped,
    CurrencyPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface CurrencyResponse
 */
export interface CurrencyResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CurrencyResponse
     */
    success: boolean;
    /**
     * 
     * @type {CurrencyPayload}
     * @memberof CurrencyResponse
     */
    payload?: CurrencyPayload;
    /**
     * 
     * @type {any}
     * @memberof CurrencyResponse
     */
    message?: any | null;
}

export function CurrencyResponseFromJSON(json: any): CurrencyResponse {
    return CurrencyResponseFromJSONTyped(json, false);
}

export function CurrencyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'payload': !exists(json, 'payload') ? undefined : CurrencyPayloadFromJSON(json['payload']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function CurrencyResponseToJSON(value?: CurrencyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'payload': CurrencyPayloadToJSON(value.payload),
        'message': value.message,
    };
}


