/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IBodyProportion
 */
export interface IBodyProportion {
    /**
     * 
     * @type {number}
     * @memberof IBodyProportion
     */
    bust?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IBodyProportion
     */
    waist?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IBodyProportion
     */
    hip?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IBodyProportion
     */
    height?: number | null;
}

export function IBodyProportionFromJSON(json: any): IBodyProportion {
    return IBodyProportionFromJSONTyped(json, false);
}

export function IBodyProportionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IBodyProportion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bust': !exists(json, 'bust') ? undefined : json['bust'],
        'waist': !exists(json, 'waist') ? undefined : json['waist'],
        'hip': !exists(json, 'hip') ? undefined : json['hip'],
        'height': !exists(json, 'height') ? undefined : json['height'],
    };
}

export function IBodyProportionToJSON(value?: IBodyProportion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bust': value.bust,
        'waist': value.waist,
        'hip': value.hip,
        'height': value.height,
    };
}


