/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ICredit
 */
export interface ICredit {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof ICredit
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof ICredit
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ICredit
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof ICredit
     */
    amount: number;
    /**
     * 
     * @type {Date}
     * @memberof ICredit
     */
    expireDate: Date;
    /**
     * 
     * @type {number}
     * @memberof ICredit
     */
    userId: number;
}

export function ICreditFromJSON(json: any): ICredit {
    return ICreditFromJSONTyped(json, false);
}

export function ICreditFromJSONTyped(json: any, ignoreDiscriminator: boolean): ICredit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'id': !exists(json, 'id') ? undefined : json['id'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'amount': json['amount'],
        'expireDate': (new Date(json['expireDate'])),
        'userId': json['UserId'],
    };
}

export function ICreditToJSON(value?: ICredit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'id': value.id,
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'amount': value.amount,
        'expireDate': (value.expireDate.toISOString()),
        'UserId': value.userId,
    };
}


