/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MEMBERTYPE,
    MEMBERTYPEFromJSON,
    MEMBERTYPEFromJSONTyped,
    MEMBERTYPEToJSON,
} from './';

/**
 * 
 * @export
 * @interface IMember
 */
export interface IMember {
    /**
     * 
     * @type {number}
     * @memberof IMember
     */
    id?: number;
    /**
     * 
     * @type {MEMBERTYPE}
     * @memberof IMember
     */
    memberType: MEMBERTYPE;
    /**
     * 
     * @type {number}
     * @memberof IMember
     */
    memberScore: number;
    /**
     * 
     * @type {string}
     * @memberof IMember
     */
    expDate: string;
}

export function IMemberFromJSON(json: any): IMember {
    return IMemberFromJSONTyped(json, false);
}

export function IMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): IMember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'memberType': MEMBERTYPEFromJSON(json['memberType']),
        'memberScore': json['memberScore'],
        'expDate': json['expDate'],
    };
}

export function IMemberToJSON(value?: IMember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'memberType': MEMBERTYPEToJSON(value.memberType),
        'memberScore': value.memberScore,
        'expDate': value.expDate,
    };
}


