/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PROMOTYPE,
    PROMOTYPEFromJSON,
    PROMOTYPEFromJSONTyped,
    PROMOTYPEToJSON,
} from './';

/**
 * 
 * @export
 * @interface IPromotion
 */
export interface IPromotion {
    /**
     * 
     * @type {number}
     * @memberof IPromotion
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof IPromotion
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IPromotion
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof IPromotion
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof IPromotion
     */
    promoCode: string;
    /**
     * 
     * @type {PROMOTYPE}
     * @memberof IPromotion
     */
    promotionType: PROMOTYPE;
    /**
     * 
     * @type {number}
     * @memberof IPromotion
     */
    totalDiscountAmt: number;
    /**
     * 
     * @type {number}
     * @memberof IPromotion
     */
    promoQty?: number;
    /**
     * 
     * @type {number}
     * @memberof IPromotion
     */
    promoLimit?: number;
    /**
     * 
     * @type {Date}
     * @memberof IPromotion
     */
    dateStart?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IPromotion
     */
    dateEnd?: Date;
}

export function IPromotionFromJSON(json: any): IPromotion {
    return IPromotionFromJSONTyped(json, false);
}

export function IPromotionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IPromotion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'title': json['title'],
        'promoCode': json['promo_code'],
        'promotionType': PROMOTYPEFromJSON(json['promotion_type']),
        'totalDiscountAmt': json['total_discount_amt'],
        'promoQty': !exists(json, 'promo_qty') ? undefined : json['promo_qty'],
        'promoLimit': !exists(json, 'promo_limit') ? undefined : json['promo_limit'],
        'dateStart': !exists(json, 'date_start') ? undefined : (new Date(json['date_start'])),
        'dateEnd': !exists(json, 'date_end') ? undefined : (new Date(json['date_end'])),
    };
}

export function IPromotionToJSON(value?: IPromotion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'title': value.title,
        'promo_code': value.promoCode,
        'promotion_type': PROMOTYPEToJSON(value.promotionType),
        'total_discount_amt': value.totalDiscountAmt,
        'promo_qty': value.promoQty,
        'promo_limit': value.promoLimit,
        'date_start': value.dateStart === undefined ? undefined : (value.dateStart.toISOString()),
        'date_end': value.dateEnd === undefined ? undefined : (value.dateEnd.toISOString()),
    };
}


