/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IProductImg,
    IProductImgFromJSON,
    IProductImgFromJSONTyped,
    IProductImgToJSON,
} from './';

/**
 * 
 * @export
 * @interface IProductImgPayload
 */
export interface IProductImgPayload {
    /**
     * 
     * @type {Array<IProductImg>}
     * @memberof IProductImgPayload
     */
    images?: Array<IProductImg>;
}

export function IProductImgPayloadFromJSON(json: any): IProductImgPayload {
    return IProductImgPayloadFromJSONTyped(json, false);
}

export function IProductImgPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): IProductImgPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'images': !exists(json, 'images') ? undefined : ((json['images'] as Array<any>).map(IProductImgFromJSON)),
    };
}

export function IProductImgPayloadToJSON(value?: IProductImgPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'images': value.images === undefined ? undefined : ((value.images as Array<any>).map(IProductImgToJSON)),
    };
}


