/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IProductImg
 */
export interface IProductImg {
    /**
     * 
     * @type {number}
     * @memberof IProductImg
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IProductImg
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof IProductImg
     */
    fileName?: string;
    /**
     * 
     * @type {number}
     * @memberof IProductImg
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof IProductImg
     */
    originalFilename?: string;
    /**
     * 
     * @type {number}
     * @memberof IProductImg
     */
    productId?: number;
}

export function IProductImgFromJSON(json: any): IProductImg {
    return IProductImgFromJSONTyped(json, false);
}

export function IProductImgFromJSONTyped(json: any, ignoreDiscriminator: boolean): IProductImg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'fileName': !exists(json, 'file_name') ? undefined : json['file_name'],
        'order': !exists(json, 'order') ? undefined : json['order'],
        'originalFilename': !exists(json, 'original_filename') ? undefined : json['original_filename'],
        'productId': !exists(json, 'ProductId') ? undefined : json['ProductId'],
    };
}

export function IProductImgToJSON(value?: IProductImg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'path': value.path,
        'file_name': value.fileName,
        'order': value.order,
        'original_filename': value.originalFilename,
        'ProductId': value.productId,
    };
}


