/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RETURNREASON,
    RETURNREASONFromJSON,
    RETURNREASONFromJSONTyped,
    RETURNREASONToJSON,
    RETURNSTATUS,
    RETURNSTATUSFromJSON,
    RETURNSTATUSFromJSONTyped,
    RETURNSTATUSToJSON,
} from './';

/**
 * 
 * @export
 * @interface IReturnOpt
 */
export interface IReturnOpt {
    /**
     * 
     * @type {RETURNSTATUS}
     * @memberof IReturnOpt
     */
    status: RETURNSTATUS;
    /**
     * 
     * @type {Array<RETURNREASON>}
     * @memberof IReturnOpt
     */
    reason: Array<RETURNREASON>;
    /**
     * 
     * @type {string}
     * @memberof IReturnOpt
     */
    rejectReason?: string;
    /**
     * 
     * @type {number}
     * @memberof IReturnOpt
     */
    qty: number;
}

export function IReturnOptFromJSON(json: any): IReturnOpt {
    return IReturnOptFromJSONTyped(json, false);
}

export function IReturnOptFromJSONTyped(json: any, ignoreDiscriminator: boolean): IReturnOpt {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': RETURNSTATUSFromJSON(json['status']),
        'reason': ((json['reason'] as Array<any>).map(RETURNREASONFromJSON)),
        'rejectReason': !exists(json, 'rejectReason') ? undefined : json['rejectReason'],
        'qty': json['qty'],
    };
}

export function IReturnOptToJSON(value?: IReturnOpt | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': RETURNSTATUSToJSON(value.status),
        'reason': ((value.reason as Array<any>).map(RETURNREASONToJSON)),
        'rejectReason': value.rejectReason,
        'qty': value.qty,
    };
}


