/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IAddress,
    IAddressFromJSON,
    IAddressFromJSONTyped,
    IAddressToJSON,
    IBodyProportion,
    IBodyProportionFromJSON,
    IBodyProportionFromJSONTyped,
    IBodyProportionToJSON,
    ICredit,
    ICreditFromJSON,
    ICreditFromJSONTyped,
    ICreditToJSON,
    ICurrency,
    ICurrencyFromJSON,
    ICurrencyFromJSONTyped,
    ICurrencyToJSON,
    IMember,
    IMemberFromJSON,
    IMemberFromJSONTyped,
    IMemberToJSON,
    ISafeCurrency,
    ISafeCurrencyFromJSON,
    ISafeCurrencyFromJSONTyped,
    ISafeCurrencyToJSON,
    IUserSettings,
    IUserSettingsFromJSON,
    IUserSettingsFromJSONTyped,
    IUserSettingsToJSON,
    USERTYPE,
    USERTYPEFromJSON,
    USERTYPEFromJSONTyped,
    USERTYPEToJSON,
} from './';

/**
 * 
 * @export
 * @interface ISafeUser
 */
export interface ISafeUser {
    /**
     * 
     * @type {number}
     * @memberof ISafeUser
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof ISafeUser
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ISafeUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ISafeUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ISafeUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof ISafeUser
     */
    nickName?: string;
    /**
     * 
     * @type {string}
     * @memberof ISafeUser
     */
    username?: string;
    /**
     * 
     * @type {USERTYPE}
     * @memberof ISafeUser
     */
    userType?: USERTYPE;
    /**
     * 
     * @type {string}
     * @memberof ISafeUser
     */
    contactNum?: string;
    /**
     * 
     * @type {string}
     * @memberof ISafeUser
     */
    dob?: string;
    /**
     * 
     * @type {string}
     * @memberof ISafeUser
     */
    email: string;
    /**
     * 
     * @type {IMember}
     * @memberof ISafeUser
     */
    member?: IMember;
    /**
     * 
     * @type {Array<IAddress>}
     * @memberof ISafeUser
     */
    addresses?: Array<IAddress>;
    /**
     * 
     * @type {IUserSettings}
     * @memberof ISafeUser
     */
    settings?: IUserSettings;
    /**
     * 
     * @type {IBodyProportion}
     * @memberof ISafeUser
     */
    bodyProportion?: IBodyProportion;
    /**
     * 
     * @type {boolean}
     * @memberof ISafeUser
     */
    active?: boolean;
    /**
     * 
     * @type {ISafeCurrency}
     * @memberof ISafeUser
     */
    defaultCurrency?: ISafeCurrency;
    /**
     * 
     * @type {number}
     * @memberof ISafeUser
     */
    creditTotal?: number;
    /**
     * 
     * @type {ICurrency}
     * @memberof ISafeUser
     */
    currency?: ICurrency;
    /**
     * 
     * @type {Array<ICredit>}
     * @memberof ISafeUser
     */
    credits: Array<ICredit>;
}

export function ISafeUserFromJSON(json: any): ISafeUser {
    return ISafeUserFromJSONTyped(json, false);
}

export function ISafeUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISafeUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'nickName': !exists(json, 'nickName') ? undefined : json['nickName'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'userType': !exists(json, 'user_type') ? undefined : USERTYPEFromJSON(json['user_type']),
        'contactNum': !exists(json, 'contactNum') ? undefined : json['contactNum'],
        'dob': !exists(json, 'dob') ? undefined : json['dob'],
        'email': json['email'],
        'member': !exists(json, 'Member') ? undefined : IMemberFromJSON(json['Member']),
        'addresses': !exists(json, 'addresses') ? undefined : ((json['addresses'] as Array<any>).map(IAddressFromJSON)),
        'settings': !exists(json, 'settings') ? undefined : IUserSettingsFromJSON(json['settings']),
        'bodyProportion': !exists(json, 'bodyProportion') ? undefined : IBodyProportionFromJSON(json['bodyProportion']),
        'active': !exists(json, 'active') ? undefined : json['active'],
        'defaultCurrency': !exists(json, 'defaultCurrency') ? undefined : ISafeCurrencyFromJSON(json['defaultCurrency']),
        'creditTotal': !exists(json, 'creditTotal') ? undefined : json['creditTotal'],
        'currency': !exists(json, 'Currency') ? undefined : ICurrencyFromJSON(json['Currency']),
        'credits': ((json['credits'] as Array<any>).map(ICreditFromJSON)),
    };
}

export function ISafeUserToJSON(value?: ISafeUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'firstName': value.firstName,
        'lastName': value.lastName,
        'nickName': value.nickName,
        'username': value.username,
        'user_type': USERTYPEToJSON(value.userType),
        'contactNum': value.contactNum,
        'dob': value.dob,
        'email': value.email,
        'Member': IMemberToJSON(value.member),
        'addresses': value.addresses === undefined ? undefined : ((value.addresses as Array<any>).map(IAddressToJSON)),
        'settings': IUserSettingsToJSON(value.settings),
        'bodyProportion': IBodyProportionToJSON(value.bodyProportion),
        'active': value.active,
        'defaultCurrency': ISafeCurrencyToJSON(value.defaultCurrency),
        'creditTotal': value.creditTotal,
        'Currency': ICurrencyToJSON(value.currency),
        'credits': ((value.credits as Array<any>).map(ICreditToJSON)),
    };
}


