/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ISafeCurrency
 */
export interface ISafeCurrency {
    /**
     * 
     * @type {string}
     * @memberof ISafeCurrency
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof ISafeCurrency
     */
    rate: number;
}

export function ISafeCurrencyFromJSON(json: any): ISafeCurrency {
    return ISafeCurrencyFromJSONTyped(json, false);
}

export function ISafeCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISafeCurrency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'rate': json['rate'],
    };
}

export function ISafeCurrencyToJSON(value?: ISafeCurrency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'rate': value.rate,
    };
}


