/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IImage,
    IImageFromJSON,
    IImageFromJSONTyped,
    IImageToJSON,
} from './';

/**
 * 
 * @export
 * @interface ISeaBannerImg
 */
export interface ISeaBannerImg {
    /**
     * 
     * @type {IImage}
     * @memberof ISeaBannerImg
     */
    img: IImage;
    /**
     * 
     * @type {string}
     * @memberof ISeaBannerImg
     */
    bannerUrl: string;
    /**
     * 
     * @type {number}
     * @memberof ISeaBannerImg
     */
    orderNo?: number;
    /**
     * 
     * @type {string}
     * @memberof ISeaBannerImg
     */
    title: string;
}

export function ISeaBannerImgFromJSON(json: any): ISeaBannerImg {
    return ISeaBannerImgFromJSONTyped(json, false);
}

export function ISeaBannerImgFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISeaBannerImg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'img': IImageFromJSON(json['img']),
        'bannerUrl': json['bannerUrl'],
        'orderNo': !exists(json, 'orderNo') ? undefined : json['orderNo'],
        'title': json['title'],
    };
}

export function ISeaBannerImgToJSON(value?: ISeaBannerImg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'img': IImageToJSON(value.img),
        'bannerUrl': value.bannerUrl,
        'orderNo': value.orderNo,
        'title': value.title,
    };
}


