/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IShipping
 */
export interface IShipping {
    /**
     * 
     * @type {number}
     * @memberof IShipping
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof IShipping
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IShipping
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof IShipping
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof IShipping
     */
    countryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof IShipping
     */
    countryName?: string;
    /**
     * 
     * @type {number}
     * @memberof IShipping
     */
    primaryRate?: number;
    /**
     * 
     * @type {number}
     * @memberof IShipping
     */
    additionalRate?: number;
}

export function IShippingFromJSON(json: any): IShipping {
    return IShippingFromJSONTyped(json, false);
}

export function IShippingFromJSONTyped(json: any, ignoreDiscriminator: boolean): IShipping {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'title': json['title'],
        'countryCode': !exists(json, 'country_code') ? undefined : json['country_code'],
        'countryName': !exists(json, 'country_name') ? undefined : json['country_name'],
        'primaryRate': !exists(json, 'primary_rate') ? undefined : json['primary_rate'],
        'additionalRate': !exists(json, 'additional_rate') ? undefined : json['additional_rate'],
    };
}

export function IShippingToJSON(value?: IShipping | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'title': value.title,
        'country_code': value.countryCode,
        'country_name': value.countryName,
        'primary_rate': value.primaryRate,
        'additional_rate': value.additionalRate,
    };
}


