/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IShippingManual
 */
export interface IShippingManual {
    /**
     * 
     * @type {number}
     * @memberof IShippingManual
     */
    manualRate?: number | null;
    /**
     * 
     * @type {string}
     * @memberof IShippingManual
     */
    salesChannel?: string | null;
}

export function IShippingManualFromJSON(json: any): IShippingManual {
    return IShippingManualFromJSONTyped(json, false);
}

export function IShippingManualFromJSONTyped(json: any, ignoreDiscriminator: boolean): IShippingManual {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'manualRate': !exists(json, 'manual_rate') ? undefined : json['manual_rate'],
        'salesChannel': !exists(json, 'sales_channel') ? undefined : json['sales_channel'],
    };
}

export function IShippingManualToJSON(value?: IShippingManual | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'manual_rate': value.manualRate,
        'sales_channel': value.salesChannel,
    };
}


