/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ISeaBannerImg,
    ISeaBannerImgFromJSON,
    ISeaBannerImgFromJSONTyped,
    ISeaBannerImgToJSON,
} from './';

/**
 * 
 * @export
 * @interface ISocialRefs
 */
export interface ISocialRefs {
    /**
     * 
     * @type {Array<ISeaBannerImg>}
     * @memberof ISocialRefs
     */
    instaImages?: Array<ISeaBannerImg>;
    /**
     * 
     * @type {string}
     * @memberof ISocialRefs
     */
    ytUrl?: string | null;
}

export function ISocialRefsFromJSON(json: any): ISocialRefs {
    return ISocialRefsFromJSONTyped(json, false);
}

export function ISocialRefsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISocialRefs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instaImages': !exists(json, 'instaImages') ? undefined : ((json['instaImages'] as Array<any>).map(ISeaBannerImgFromJSON)),
        'ytUrl': !exists(json, 'yt_url') ? undefined : json['yt_url'],
    };
}

export function ISocialRefsToJSON(value?: ISocialRefs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instaImages': value.instaImages === undefined ? undefined : ((value.instaImages as Array<any>).map(ISeaBannerImgToJSON)),
        'yt_url': value.ytUrl,
    };
}


