/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CLOTHESIZE,
    CLOTHESIZEFromJSON,
    CLOTHESIZEFromJSONTyped,
    CLOTHESIZEToJSON,
    IProduct,
    IProductFromJSON,
    IProductFromJSONTyped,
    IProductToJSON,
    IStockLocation,
    IStockLocationFromJSON,
    IStockLocationFromJSONTyped,
    IStockLocationToJSON,
} from './';

/**
 * 
 * @export
 * @interface IStock
 */
export interface IStock {
    /**
     * 
     * @type {number}
     * @memberof IStock
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof IStock
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IStock
     */
    createdAt?: Date;
    /**
     * 
     * @type {CLOTHESIZE | number}
     * @memberof IStock
     */
    size: CLOTHESIZE | number;
    /**
     * 
     * @type {number}
     * @memberof IStock
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof IStock
     */
    preOrderDays?: number;
    /**
     * 
     * @type {IProduct}
     * @memberof IStock
     */
    product: IProduct;
    /**
     * 
     * @type {IStockLocation}
     * @memberof IStock
     */
    stockLocation: IStockLocation;
}

export function IStockFromJSON(json: any): IStock {
    return IStockFromJSONTyped(json, false);
}

export function IStockFromJSONTyped(json: any, ignoreDiscriminator: boolean): IStock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'size': CLOTHESIZE | numberFromJSON(json['size']),
        'quantity': json['quantity'],
        'preOrderDays': !exists(json, 'preOrderDays') ? undefined : json['preOrderDays'],
        'product': IProductFromJSON(json['product']),
        'stockLocation': IStockLocationFromJSON(json['StockLocation']),
    };
}

export function IStockToJSON(value?: IStock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'size': CLOTHESIZE | numberToJSON(value.size),
        'quantity': value.quantity,
        'preOrderDays': value.preOrderDays,
        'product': IProductToJSON(value.product),
        'StockLocation': IStockLocationToJSON(value.stockLocation),
    };
}


