/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IBannerImg,
    IBannerImgFromJSON,
    IBannerImgFromJSONTyped,
    IBannerImgToJSON,
} from './';

/**
 * 
 * @export
 * @interface IUpdateMainBanners
 */
export interface IUpdateMainBanners {
    /**
     * 
     * @type {Array<IBannerImg>}
     * @memberof IUpdateMainBanners
     */
    mainBanners: Array<IBannerImg>;
}

export function IUpdateMainBannersFromJSON(json: any): IUpdateMainBanners {
    return IUpdateMainBannersFromJSONTyped(json, false);
}

export function IUpdateMainBannersFromJSONTyped(json: any, ignoreDiscriminator: boolean): IUpdateMainBanners {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mainBanners': ((json['mainBanners'] as Array<any>).map(IBannerImgFromJSON)),
    };
}

export function IUpdateMainBannersToJSON(value?: IUpdateMainBanners | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mainBanners': ((value.mainBanners as Array<any>).map(IBannerImgToJSON)),
    };
}


