/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum LANGUAGE {
    EN = 'EN',
    TH = 'TH'
}

export function LANGUAGEFromJSON(json: any): LANGUAGE {
    return LANGUAGEFromJSONTyped(json, false);
}

export function LANGUAGEFromJSONTyped(json: any, ignoreDiscriminator: boolean): LANGUAGE {
    return json as LANGUAGE;
}

export function LANGUAGEToJSON(value?: LANGUAGE | null): any {
    return value as any;
}

