/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MEMBERTYPE {
    VIP = 'VIP',
    STANDARD = 'STANDARD'
}

export function MEMBERTYPEFromJSON(json: any): MEMBERTYPE {
    return MEMBERTYPEFromJSONTyped(json, false);
}

export function MEMBERTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): MEMBERTYPE {
    return json as MEMBERTYPE;
}

export function MEMBERTYPEToJSON(value?: MEMBERTYPE | null): any {
    return value as any;
}

