/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NotificationPayload,
    NotificationPayloadFromJSON,
    NotificationPayloadFromJSONTyped,
    NotificationPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface NotificationResponse
 */
export interface NotificationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof NotificationResponse
     */
    success: boolean;
    /**
     * 
     * @type {NotificationPayload}
     * @memberof NotificationResponse
     */
    payload?: NotificationPayload;
    /**
     * 
     * @type {any}
     * @memberof NotificationResponse
     */
    message?: any | null;
}

export function NotificationResponseFromJSON(json: any): NotificationResponse {
    return NotificationResponseFromJSONTyped(json, false);
}

export function NotificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'payload': !exists(json, 'payload') ? undefined : NotificationPayloadFromJSON(json['payload']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function NotificationResponseToJSON(value?: NotificationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'payload': NotificationPayloadToJSON(value.payload),
        'message': value.message,
    };
}


