/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NOTIFICATIONTYPE,
    NOTIFICATIONTYPEFromJSON,
    NOTIFICATIONTYPEFromJSONTyped,
    NOTIFICATIONTYPEToJSON,
} from './';

/**
 * 
 * @export
 * @interface NotificationReq
 */
export interface NotificationReq {
    /**
     * 
     * @type {string}
     * @memberof NotificationReq
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationReq
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationReq
     */
    active?: boolean;
    /**
     * 
     * @type {NOTIFICATIONTYPE}
     * @memberof NotificationReq
     */
    notiType?: NOTIFICATIONTYPE;
}

export function NotificationReqFromJSON(json: any): NotificationReq {
    return NotificationReqFromJSONTyped(json, false);
}

export function NotificationReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'notiType': !exists(json, 'noti_type') ? undefined : NOTIFICATIONTYPEFromJSON(json['noti_type']),
    };
}

export function NotificationReqToJSON(value?: NotificationReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'url': value.url,
        'active': value.active,
        'noti_type': NOTIFICATIONTYPEToJSON(value.notiType),
    };
}


