/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IShippingManual,
    IShippingManualFromJSON,
    IShippingManualFromJSONTyped,
    IShippingManualToJSON,
} from './';

/**
 * 
 * @export
 * @interface NullableIShippingManual
 */
export interface NullableIShippingManual extends IShippingManual {
}

export function NullableIShippingManualFromJSON(json: any): NullableIShippingManual {
    return NullableIShippingManualFromJSONTyped(json, false);
}

export function NullableIShippingManualFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableIShippingManual {
    return json;
}

export function NullableIShippingManualToJSON(value?: NullableIShippingManual | null): any {
    return value;
}


