/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ORDERSOURCE,
    ORDERSOURCEFromJSON,
    ORDERSOURCEFromJSONTyped,
    ORDERSOURCEToJSON,
} from './';

/**
 * 
 * @export
 * @interface NullableORDERSOURCE
 */
export interface NullableORDERSOURCE extends ORDERSOURCE {
}

export function NullableORDERSOURCEFromJSON(json: any): NullableORDERSOURCE {
    return NullableORDERSOURCEFromJSONTyped(json, false);
}

export function NullableORDERSOURCEFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableORDERSOURCE {
    return json;
}

export function NullableORDERSOURCEToJSON(value?: NullableORDERSOURCE | null): any {
    return value;
}


