/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DiscountItemObj,
    DiscountItemObjFromJSON,
    DiscountItemObjFromJSONTyped,
    DiscountItemObjToJSON,
    IProduct,
    IProductFromJSON,
    IProductFromJSONTyped,
    IProductToJSON,
    IStock,
    IStockFromJSON,
    IStockFromJSONTyped,
    IStockToJSON,
    NullableIReturnOpt,
    NullableIReturnOptFromJSON,
    NullableIReturnOptFromJSONTyped,
    NullableIReturnOptToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrderProducts
 */
export interface OrderProducts {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof OrderProducts
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderProducts
     */
    qty: number;
    /**
     * 
     * @type {IProduct}
     * @memberof OrderProducts
     */
    product: IProduct;
    /**
     * 
     * @type {number}
     * @memberof OrderProducts
     */
    tradePrice?: number;
    /**
     * 
     * @type {IStock}
     * @memberof OrderProducts
     */
    stock: IStock;
    /**
     * 
     * @type {DiscountItemObj}
     * @memberof OrderProducts
     */
    discountPerItem?: DiscountItemObj;
    /**
     * 
     * @type {NullableIReturnOpt}
     * @memberof OrderProducts
     */
    returnOpt?: NullableIReturnOpt | null;
}

export function OrderProductsFromJSON(json: any): OrderProducts {
    return OrderProductsFromJSONTyped(json, false);
}

export function OrderProductsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderProducts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'id': !exists(json, 'id') ? undefined : json['id'],
        'qty': json['qty'],
        'product': IProductFromJSON(json['product']),
        'tradePrice': !exists(json, 'trade_price') ? undefined : json['trade_price'],
        'stock': IStockFromJSON(json['stock']),
        'discountPerItem': !exists(json, 'discountPerItem') ? undefined : DiscountItemObjFromJSON(json['discountPerItem']),
        'returnOpt': !exists(json, 'returnOpt') ? undefined : NullableIReturnOptFromJSON(json['returnOpt']),
    };
}

export function OrderProductsToJSON(value?: OrderProducts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'id': value.id,
        'qty': value.qty,
        'product': IProductToJSON(value.product),
        'trade_price': value.tradePrice,
        'stock': IStockToJSON(value.stock),
        'discountPerItem': DiscountItemObjToJSON(value.discountPerItem),
        'returnOpt': NullableIReturnOptToJSON(value.returnOpt),
    };
}


