/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OPReturn,
    OPReturnFromJSON,
    OPReturnFromJSONTyped,
    OPReturnToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrderReturn
 */
export interface OrderReturn {
    /**
     * 
     * @type {Array<OPReturn>}
     * @memberof OrderReturn
     */
    orderProducts: Array<OPReturn>;
    /**
     * 
     * @type {number}
     * @memberof OrderReturn
     */
    orderId: number;
}

export function OrderReturnFromJSON(json: any): OrderReturn {
    return OrderReturnFromJSONTyped(json, false);
}

export function OrderReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderReturn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderProducts': ((json['orderProducts'] as Array<any>).map(OPReturnFromJSON)),
        'orderId': json['orderId'],
    };
}

export function OrderReturnToJSON(value?: OrderReturn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderProducts': ((value.orderProducts as Array<any>).map(OPReturnToJSON)),
        'orderId': value.orderId,
    };
}


