/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DiscountItemObj,
    DiscountItemObjFromJSON,
    DiscountItemObjFromJSONTyped,
    DiscountItemObjToJSON,
    IShippingManual,
    IShippingManualFromJSON,
    IShippingManualFromJSONTyped,
    IShippingManualToJSON,
    ORDERSOURCE,
    ORDERSOURCEFromJSON,
    ORDERSOURCEFromJSONTyped,
    ORDERSOURCEToJSON,
    OrderProductsReq,
    OrderProductsReqFromJSON,
    OrderProductsReqFromJSONTyped,
    OrderProductsReqToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrderSim
 */
export interface OrderSim {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<OrderProductsReq>}
     * @memberof OrderSim
     */
    orderProducts: Array<OrderProductsReq>;
    /**
     * 
     * @type {ORDERSOURCE}
     * @memberof OrderSim
     */
    orderSource: ORDERSOURCE;
    /**
     * 
     * @type {number}
     * @memberof OrderSim
     */
    customerId: number;
    /**
     * 
     * @type {string}
     * @memberof OrderSim
     */
    promoCode?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderSim
     */
    shippingId?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderSim
     */
    creditTotal?: number | null;
    /**
     * 
     * @type {DiscountItemObj}
     * @memberof OrderSim
     */
    discountPerOrder?: DiscountItemObj;
    /**
     * 
     * @type {IShippingManual}
     * @memberof OrderSim
     */
    shippingManual?: IShippingManual;
}

export function OrderSimFromJSON(json: any): OrderSim {
    return OrderSimFromJSONTyped(json, false);
}

export function OrderSimFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderSim {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'orderProducts': ((json['orderProducts'] as Array<any>).map(OrderProductsReqFromJSON)),
        'orderSource': ORDERSOURCEFromJSON(json['orderSource']),
        'customerId': json['customerId'],
        'promoCode': !exists(json, 'promo_code') ? undefined : json['promo_code'],
        'shippingId': !exists(json, 'shippingId') ? undefined : json['shippingId'],
        'creditTotal': !exists(json, 'creditTotal') ? undefined : json['creditTotal'],
        'discountPerOrder': !exists(json, 'discountPerOrder') ? undefined : DiscountItemObjFromJSON(json['discountPerOrder']),
        'shippingManual': !exists(json, 'shippingManual') ? undefined : IShippingManualFromJSON(json['shippingManual']),
    };
}

export function OrderSimToJSON(value?: OrderSim | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'orderProducts': ((value.orderProducts as Array<any>).map(OrderProductsReqToJSON)),
        'orderSource': ORDERSOURCEToJSON(value.orderSource),
        'customerId': value.customerId,
        'promo_code': value.promoCode,
        'shippingId': value.shippingId,
        'creditTotal': value.creditTotal,
        'discountPerOrder': DiscountItemObjToJSON(value.discountPerOrder),
        'shippingManual': IShippingManualToJSON(value.shippingManual),
    };
}


