/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IAddress,
    IAddressFromJSON,
    IAddressFromJSONTyped,
    IAddressToJSON,
    ICurrency,
    ICurrencyFromJSON,
    ICurrencyFromJSONTyped,
    ICurrencyToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrderRefs
 */
export interface OrderRefs {
    /**
     * 
     * @type {IAddress}
     * @memberof OrderRefs
     */
    address?: IAddress;
    /**
     * 
     * @type {IAddress}
     * @memberof OrderRefs
     */
    taxAddress?: IAddress;
    /**
     * 
     * @type {ICurrency}
     * @memberof OrderRefs
     */
    currency: ICurrency;
}

export function OrderRefsFromJSON(json: any): OrderRefs {
    return OrderRefsFromJSONTyped(json, false);
}

export function OrderRefsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderRefs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': !exists(json, 'address') ? undefined : IAddressFromJSON(json['address']),
        'taxAddress': !exists(json, 'taxAddress') ? undefined : IAddressFromJSON(json['taxAddress']),
        'currency': ICurrencyFromJSON(json['currency']),
    };
}

export function OrderRefsToJSON(value?: OrderRefs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': IAddressToJSON(value.address),
        'taxAddress': IAddressToJSON(value.taxAddress),
        'currency': ICurrencyToJSON(value.currency),
    };
}


