/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IShippingManual,
    IShippingManualFromJSON,
    IShippingManualFromJSONTyped,
    IShippingManualToJSON,
    NullableDiscountItemObj,
    NullableDiscountItemObjFromJSON,
    NullableDiscountItemObjFromJSONTyped,
    NullableDiscountItemObjToJSON,
    OrderProductsReq,
    OrderProductsReqFromJSON,
    OrderProductsReqFromJSONTyped,
    OrderProductsReqToJSON,
    PaymentDetails,
    PaymentDetailsFromJSON,
    PaymentDetailsFromJSONTyped,
    PaymentDetailsToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrderReqManual
 */
export interface OrderReqManual {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<OrderProductsReq>}
     * @memberof OrderReqManual
     */
    orderProducts: Array<OrderProductsReq>;
    /**
     * 
     * @type {IShippingManual}
     * @memberof OrderReqManual
     */
    shippingManual: IShippingManual;
    /**
     * 
     * @type {number}
     * @memberof OrderReqManual
     */
    customerId: number;
    /**
     * 
     * @type {string}
     * @memberof OrderReqManual
     */
    promoCode?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrderReqManual
     */
    isReqTax?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof OrderReqManual
     */
    taxId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderReqManual
     */
    specialRequest?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderReqManual
     */
    trackingNo?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OrderReqManual
     */
    trackingDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof OrderReqManual
     */
    addressId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OrderReqManual
     */
    taxAddressId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OrderReqManual
     */
    creditTotal?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OrderReqManual
     */
    currencyId?: number | null;
    /**
     * 
     * @type {NullableDiscountItemObj}
     * @memberof OrderReqManual
     */
    discountPerOrder?: NullableDiscountItemObj | null;
    /**
     * 
     * @type {Array<PaymentDetails>}
     * @memberof OrderReqManual
     */
    payment: Array<PaymentDetails>;
    /**
     * 
     * @type {number}
     * @memberof OrderReqManual
     */
    adminId: number;
    /**
     * 
     * @type {string}
     * @memberof OrderReqManual
     */
    remarks?: string | null;
}

export function OrderReqManualFromJSON(json: any): OrderReqManual {
    return OrderReqManualFromJSONTyped(json, false);
}

export function OrderReqManualFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderReqManual {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'orderProducts': ((json['orderProducts'] as Array<any>).map(OrderProductsReqFromJSON)),
        'shippingManual': IShippingManualFromJSON(json['shippingManual']),
        'customerId': json['customerId'],
        'promoCode': !exists(json, 'promo_code') ? undefined : json['promo_code'],
        'isReqTax': !exists(json, 'isReqTax') ? undefined : json['isReqTax'],
        'taxId': !exists(json, 'taxId') ? undefined : json['taxId'],
        'specialRequest': !exists(json, 'specialRequest') ? undefined : json['specialRequest'],
        'trackingNo': !exists(json, 'trackingNo') ? undefined : json['trackingNo'],
        'trackingDate': !exists(json, 'trackingDate') ? undefined : (json['trackingDate'] === null ? null : new Date(json['trackingDate'])),
        'addressId': !exists(json, 'addressId') ? undefined : json['addressId'],
        'taxAddressId': !exists(json, 'taxAddressId') ? undefined : json['taxAddressId'],
        'creditTotal': !exists(json, 'creditTotal') ? undefined : json['creditTotal'],
        'currencyId': !exists(json, 'currencyId') ? undefined : json['currencyId'],
        'discountPerOrder': !exists(json, 'discountPerOrder') ? undefined : NullableDiscountItemObjFromJSON(json['discountPerOrder']),
        'payment': ((json['payment'] as Array<any>).map(PaymentDetailsFromJSON)),
        'adminId': json['adminId'],
        'remarks': !exists(json, 'remarks') ? undefined : json['remarks'],
    };
}

export function OrderReqManualToJSON(value?: OrderReqManual | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'orderProducts': ((value.orderProducts as Array<any>).map(OrderProductsReqToJSON)),
        'shippingManual': IShippingManualToJSON(value.shippingManual),
        'customerId': value.customerId,
        'promo_code': value.promoCode,
        'isReqTax': value.isReqTax,
        'taxId': value.taxId,
        'specialRequest': value.specialRequest,
        'trackingNo': value.trackingNo,
        'trackingDate': value.trackingDate === undefined ? undefined : (value.trackingDate === null ? null : value.trackingDate.toISOString()),
        'addressId': value.addressId,
        'taxAddressId': value.taxAddressId,
        'creditTotal': value.creditTotal,
        'currencyId': value.currencyId,
        'discountPerOrder': NullableDiscountItemObjToJSON(value.discountPerOrder),
        'payment': ((value.payment as Array<any>).map(PaymentDetailsToJSON)),
        'adminId': value.adminId,
        'remarks': value.remarks,
    };
}


