/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderPayload,
    OrderPayloadFromJSON,
    OrderPayloadFromJSONTyped,
    OrderPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrderResponse
 */
export interface OrderResponse {
    /**
     * 
     * @type {boolean}
     * @memberof OrderResponse
     */
    success: boolean;
    /**
     * 
     * @type {OrderPayload}
     * @memberof OrderResponse
     */
    payload?: OrderPayload;
    /**
     * 
     * @type {any}
     * @memberof OrderResponse
     */
    message?: any | null;
}

export function OrderResponseFromJSON(json: any): OrderResponse {
    return OrderResponseFromJSONTyped(json, false);
}

export function OrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'payload': !exists(json, 'payload') ? undefined : OrderPayloadFromJSON(json['payload']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function OrderResponseToJSON(value?: OrderResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'payload': OrderPayloadToJSON(value.payload),
        'message': value.message,
    };
}


