/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ORDERSTATUS {
    SUCCESS = 'SUCCESS',
    PENDINGDLVR = 'PENDING_DLVR',
    CANCEL = 'CANCEL'
}

export function ORDERSTATUSFromJSON(json: any): ORDERSTATUS {
    return ORDERSTATUSFromJSONTyped(json, false);
}

export function ORDERSTATUSFromJSONTyped(json: any, ignoreDiscriminator: boolean): ORDERSTATUS {
    return json as ORDERSTATUS;
}

export function ORDERSTATUSToJSON(value?: ORDERSTATUS | null): any {
    return value as any;
}

