/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OverridePassReq
 */
export interface OverridePassReq {
    /**
     * 
     * @type {number}
     * @memberof OverridePassReq
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof OverridePassReq
     */
    newPass: string;
}

export function OverridePassReqFromJSON(json: any): OverridePassReq {
    return OverridePassReqFromJSONTyped(json, false);
}

export function OverridePassReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverridePassReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'newPass': json['newPass'],
    };
}

export function OverridePassReqToJSON(value?: OverridePassReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'newPass': value.newPass,
    };
}


