/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PAYMENTTYPE {
    QR = 'QR',
    PAYGATE = 'PAYGATE',
    P2PDIRECT = 'P2P_DIRECT',
    MANUAL = 'MANUAL'
}

export function PAYMENTTYPEFromJSON(json: any): PAYMENTTYPE {
    return PAYMENTTYPEFromJSONTyped(json, false);
}

export function PAYMENTTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): PAYMENTTYPE {
    return json as PAYMENTTYPE;
}

export function PAYMENTTYPEToJSON(value?: PAYMENTTYPE | null): any {
    return value as any;
}

