/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentDetails
 */
export interface PaymentDetails {
    /**
     * 
     * @type {number}
     * @memberof PaymentDetails
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentDetails
     */
    channel: string;
    /**
     * 
     * @type {Date}
     * @memberof PaymentDetails
     */
    payDate: Date;
}

export function PaymentDetailsFromJSON(json: any): PaymentDetails {
    return PaymentDetailsFromJSONTyped(json, false);
}

export function PaymentDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'index': json['index'],
        'amount': json['amount'],
        'channel': json['channel'],
        'payDate': (new Date(json['payDate'])),
    };
}

export function PaymentDetailsToJSON(value?: PaymentDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'index': value.index,
        'amount': value.amount,
        'channel': value.channel,
        'payDate': (value.payDate.toISOString()),
    };
}


