/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IProduct,
    IProductFromJSON,
    IProductFromJSONTyped,
    IProductToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductPayload
 */
export interface ProductPayload {
    /**
     * 
     * @type {IProduct}
     * @memberof ProductPayload
     */
    product?: IProduct;
    /**
     * 
     * @type {Array<IProduct>}
     * @memberof ProductPayload
     */
    products?: Array<IProduct>;
    /**
     * 
     * @type {number}
     * @memberof ProductPayload
     */
    listLength?: number;
}

export function ProductPayloadFromJSON(json: any): ProductPayload {
    return ProductPayloadFromJSONTyped(json, false);
}

export function ProductPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'product': !exists(json, 'product') ? undefined : IProductFromJSON(json['product']),
        'products': !exists(json, 'products') ? undefined : ((json['products'] as Array<any>).map(IProductFromJSON)),
        'listLength': !exists(json, 'listLength') ? undefined : json['listLength'],
    };
}

export function ProductPayloadToJSON(value?: ProductPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product': IProductToJSON(value.product),
        'products': value.products === undefined ? undefined : ((value.products as Array<any>).map(IProductToJSON)),
        'listLength': value.listLength,
    };
}


