/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PRODUCTTYPE {
    CLOTHES = 'CLOTHES',
    SHOES = 'SHOES'
}

export function PRODUCTTYPEFromJSON(json: any): PRODUCTTYPE {
    return PRODUCTTYPEFromJSONTyped(json, false);
}

export function PRODUCTTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): PRODUCTTYPE {
    return json as PRODUCTTYPE;
}

export function PRODUCTTYPEToJSON(value?: PRODUCTTYPE | null): any {
    return value as any;
}

