/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IPromotion,
    IPromotionFromJSON,
    IPromotionFromJSONTyped,
    IPromotionToJSON,
} from './';

/**
 * 
 * @export
 * @interface PromotionPayload
 */
export interface PromotionPayload {
    /**
     * 
     * @type {IPromotion}
     * @memberof PromotionPayload
     */
    promotion?: IPromotion;
    /**
     * 
     * @type {Array<IPromotion>}
     * @memberof PromotionPayload
     */
    promotions?: Array<IPromotion>;
    /**
     * 
     * @type {number}
     * @memberof PromotionPayload
     */
    listLength?: number;
    /**
     * 
     * @type {string}
     * @memberof PromotionPayload
     */
    msg?: string;
}

export function PromotionPayloadFromJSON(json: any): PromotionPayload {
    return PromotionPayloadFromJSONTyped(json, false);
}

export function PromotionPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotionPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'promotion': !exists(json, 'promotion') ? undefined : IPromotionFromJSON(json['promotion']),
        'promotions': !exists(json, 'promotions') ? undefined : ((json['promotions'] as Array<any>).map(IPromotionFromJSON)),
        'listLength': !exists(json, 'listLength') ? undefined : json['listLength'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
    };
}

export function PromotionPayloadToJSON(value?: PromotionPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'promotion': IPromotionToJSON(value.promotion),
        'promotions': value.promotions === undefined ? undefined : ((value.promotions as Array<any>).map(IPromotionToJSON)),
        'listLength': value.listLength,
        'msg': value.msg,
    };
}


