/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PROMOTYPE {
    PERCENTAGE = 'PERCENTAGE',
    BAHTDISCOUNT = 'BAHT_DISCOUNT'
}

export function PROMOTYPEFromJSON(json: any): PROMOTYPE {
    return PROMOTYPEFromJSONTyped(json, false);
}

export function PROMOTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): PROMOTYPE {
    return json as PROMOTYPE;
}

export function PROMOTYPEToJSON(value?: PROMOTYPE | null): any {
    return value as any;
}

