/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromoVerify
 */
export interface PromoVerify {
    /**
     * 
     * @type {string}
     * @memberof PromoVerify
     */
    promoCode: string;
}

export function PromoVerifyFromJSON(json: any): PromoVerify {
    return PromoVerifyFromJSONTyped(json, false);
}

export function PromoVerifyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromoVerify {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'promoCode': json['promo_code'],
    };
}

export function PromoVerifyToJSON(value?: PromoVerify | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'promo_code': value.promoCode,
    };
}


