/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPassReq
 */
export interface ResetPassReq {
    /**
     * 
     * @type {string}
     * @memberof ResetPassReq
     */
    resetToken: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPassReq
     */
    password: string;
}

export function ResetPassReqFromJSON(json: any): ResetPassReq {
    return ResetPassReqFromJSONTyped(json, false);
}

export function ResetPassReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPassReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resetToken': json['resetToken'],
        'password': json['password'],
    };
}

export function ResetPassReqToJSON(value?: ResetPassReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resetToken': value.resetToken,
        'password': value.password,
    };
}


