/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RETURNREASON {
    TOOBIG = 'TOO_BIG',
    TOOSMALL = 'TOO_SMALL',
    PRODUCTQUALITY = 'PRODUCT_QUALITY',
    PHOTODIFF = 'PHOTO_DIFF',
    WRONGITEM = 'WRONG_ITEM',
    FAULTYITEM = 'FAULTY_ITEM',
    LATEDELIVERY = 'LATE_DELIVERY'
}

export function RETURNREASONFromJSON(json: any): RETURNREASON {
    return RETURNREASONFromJSONTyped(json, false);
}

export function RETURNREASONFromJSONTyped(json: any, ignoreDiscriminator: boolean): RETURNREASON {
    return json as RETURNREASON;
}

export function RETURNREASONToJSON(value?: RETURNREASON | null): any {
    return value as any;
}

