/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RETURNSTATUSREQ {
    ALL = 'ALL',
    NONE = 'NONE',
    OTW = 'OTW',
    DONE = 'DONE'
}

export function RETURNSTATUSREQFromJSON(json: any): RETURNSTATUSREQ {
    return RETURNSTATUSREQFromJSONTyped(json, false);
}

export function RETURNSTATUSREQFromJSONTyped(json: any, ignoreDiscriminator: boolean): RETURNSTATUSREQ {
    return json as RETURNSTATUSREQ;
}

export function RETURNSTATUSREQToJSON(value?: RETURNSTATUSREQ | null): any {
    return value as any;
}

