/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RETURNSTATUS {
    NONE = 'NONE',
    OTW = 'OTW',
    DONE = 'DONE'
}

export function RETURNSTATUSFromJSON(json: any): RETURNSTATUS {
    return RETURNSTATUSFromJSONTyped(json, false);
}

export function RETURNSTATUSFromJSONTyped(json: any, ignoreDiscriminator: boolean): RETURNSTATUS {
    return json as RETURNSTATUS;
}

export function RETURNSTATUSToJSON(value?: RETURNSTATUS | null): any {
    return value as any;
}

