/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OPOptConfirm,
    OPOptConfirmFromJSON,
    OPOptConfirmFromJSONTyped,
    OPOptConfirmToJSON,
} from './';

/**
 * 
 * @export
 * @interface ReturnOptConfirm
 */
export interface ReturnOptConfirm {
    /**
     * 
     * @type {Array<OPOptConfirm>}
     * @memberof ReturnOptConfirm
     */
    orderProducts: Array<OPOptConfirm>;
    /**
     * 
     * @type {number}
     * @memberof ReturnOptConfirm
     */
    orderId: number;
}

export function ReturnOptConfirmFromJSON(json: any): ReturnOptConfirm {
    return ReturnOptConfirmFromJSONTyped(json, false);
}

export function ReturnOptConfirmFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnOptConfirm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderProducts': ((json['orderProducts'] as Array<any>).map(OPOptConfirmFromJSON)),
        'orderId': json['orderId'],
    };
}

export function ReturnOptConfirmToJSON(value?: ReturnOptConfirm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderProducts': ((value.orderProducts as Array<any>).map(OPOptConfirmToJSON)),
        'orderId': value.orderId,
    };
}


