/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShippingReq
 */
export interface ShippingReq {
    /**
     * 
     * @type {string}
     * @memberof ShippingReq
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShippingReq
     */
    countryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShippingReq
     */
    countryName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ShippingReq
     */
    primaryRate?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ShippingReq
     */
    additionalRate?: number | null;
}

export function ShippingReqFromJSON(json: any): ShippingReq {
    return ShippingReqFromJSONTyped(json, false);
}

export function ShippingReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'countryCode': !exists(json, 'country_code') ? undefined : json['country_code'],
        'countryName': !exists(json, 'country_name') ? undefined : json['country_name'],
        'primaryRate': !exists(json, 'primary_rate') ? undefined : json['primary_rate'],
        'additionalRate': !exists(json, 'additional_rate') ? undefined : json['additional_rate'],
    };
}

export function ShippingReqToJSON(value?: ShippingReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'country_code': value.countryCode,
        'country_name': value.countryName,
        'primary_rate': value.primaryRate,
        'additional_rate': value.additionalRate,
    };
}


