/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IShipping,
    IShippingFromJSON,
    IShippingFromJSONTyped,
    IShippingToJSON,
} from './';

/**
 * 
 * @export
 * @interface ShippingPayload
 */
export interface ShippingPayload {
    /**
     * 
     * @type {Array<any>}
     * @memberof ShippingPayload
     */
    countries?: Array<any>;
    /**
     * 
     * @type {IShipping}
     * @memberof ShippingPayload
     */
    shipping?: IShipping;
    /**
     * 
     * @type {Array<IShipping>}
     * @memberof ShippingPayload
     */
    shipments?: Array<IShipping>;
    /**
     * 
     * @type {number}
     * @memberof ShippingPayload
     */
    listLength?: number;
}

export function ShippingPayloadFromJSON(json: any): ShippingPayload {
    return ShippingPayloadFromJSONTyped(json, false);
}

export function ShippingPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'countries': !exists(json, 'countries') ? undefined : json['countries'],
        'shipping': !exists(json, 'shipping') ? undefined : IShippingFromJSON(json['shipping']),
        'shipments': !exists(json, 'shipments') ? undefined : ((json['shipments'] as Array<any>).map(IShippingFromJSON)),
        'listLength': !exists(json, 'listLength') ? undefined : json['listLength'],
    };
}

export function ShippingPayloadToJSON(value?: ShippingPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'countries': value.countries,
        'shipping': IShippingToJSON(value.shipping),
        'shipments': value.shipments === undefined ? undefined : ((value.shipments as Array<any>).map(IShippingToJSON)),
        'listLength': value.listLength,
    };
}


