/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ShippingPayload,
    ShippingPayloadFromJSON,
    ShippingPayloadFromJSONTyped,
    ShippingPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface ShippingResponse
 */
export interface ShippingResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ShippingResponse
     */
    success: boolean;
    /**
     * 
     * @type {ShippingPayload}
     * @memberof ShippingResponse
     */
    payload?: ShippingPayload;
    /**
     * 
     * @type {any}
     * @memberof ShippingResponse
     */
    message?: any | null;
}

export function ShippingResponseFromJSON(json: any): ShippingResponse {
    return ShippingResponseFromJSONTyped(json, false);
}

export function ShippingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'payload': !exists(json, 'payload') ? undefined : ShippingPayloadFromJSON(json['payload']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ShippingResponseToJSON(value?: ShippingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'payload': ShippingPayloadToJSON(value.payload),
        'message': value.message,
    };
}


