/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ISafeStockLocation,
    ISafeStockLocationFromJSON,
    ISafeStockLocationFromJSONTyped,
    ISafeStockLocationToJSON,
} from './';

/**
 * 
 * @export
 * @interface StockLocationPayload
 */
export interface StockLocationPayload {
    /**
     * 
     * @type {ISafeStockLocation}
     * @memberof StockLocationPayload
     */
    stockLocation?: ISafeStockLocation;
    /**
     * 
     * @type {Array<ISafeStockLocation>}
     * @memberof StockLocationPayload
     */
    stockLocations?: Array<ISafeStockLocation>;
    /**
     * 
     * @type {number}
     * @memberof StockLocationPayload
     */
    listLength?: number;
}

export function StockLocationPayloadFromJSON(json: any): StockLocationPayload {
    return StockLocationPayloadFromJSONTyped(json, false);
}

export function StockLocationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockLocationPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stockLocation': !exists(json, 'stockLocation') ? undefined : ISafeStockLocationFromJSON(json['stockLocation']),
        'stockLocations': !exists(json, 'stockLocations') ? undefined : ((json['stockLocations'] as Array<any>).map(ISafeStockLocationFromJSON)),
        'listLength': !exists(json, 'listLength') ? undefined : json['listLength'],
    };
}

export function StockLocationPayloadToJSON(value?: StockLocationPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stockLocation': ISafeStockLocationToJSON(value.stockLocation),
        'stockLocations': value.stockLocations === undefined ? undefined : ((value.stockLocations as Array<any>).map(ISafeStockLocationToJSON)),
        'listLength': value.listLength,
    };
}


