/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StockLocationReq
 */
export interface StockLocationReq {
    /**
     * 
     * @type {string}
     * @memberof StockLocationReq
     */
    title: string;
}

export function StockLocationReqFromJSON(json: any): StockLocationReq {
    return StockLocationReqFromJSONTyped(json, false);
}

export function StockLocationReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockLocationReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function StockLocationReqToJSON(value?: StockLocationReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
    };
}


