/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StockReq
 */
export interface StockReq {
    /**
     * 
     * @type {string}
     * @memberof StockReq
     */
    size: string;
    /**
     * 
     * @type {number}
     * @memberof StockReq
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof StockReq
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof StockReq
     */
    preOrderDays?: number;
    /**
     * 
     * @type {number}
     * @memberof StockReq
     */
    stockLocationId: number;
}

export function StockReqFromJSON(json: any): StockReq {
    return StockReqFromJSONTyped(json, false);
}

export function StockReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'size': json['size'],
        'quantity': json['quantity'],
        'productId': !exists(json, 'ProductId') ? undefined : json['ProductId'],
        'preOrderDays': !exists(json, 'preOrderDays') ? undefined : json['preOrderDays'],
        'stockLocationId': json['StockLocationId'],
    };
}

export function StockReqToJSON(value?: StockReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'size': value.size,
        'quantity': value.quantity,
        'ProductId': value.productId,
        'preOrderDays': value.preOrderDays,
        'StockLocationId': value.stockLocationId,
    };
}


