/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StockPayload,
    StockPayloadFromJSON,
    StockPayloadFromJSONTyped,
    StockPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface StockResponse
 */
export interface StockResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StockResponse
     */
    success: boolean;
    /**
     * 
     * @type {StockPayload}
     * @memberof StockResponse
     */
    payload?: StockPayload;
    /**
     * 
     * @type {any}
     * @memberof StockResponse
     */
    message?: any | null;
}

export function StockResponseFromJSON(json: any): StockResponse {
    return StockResponseFromJSONTyped(json, false);
}

export function StockResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'payload': !exists(json, 'payload') ? undefined : StockPayloadFromJSON(json['payload']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function StockResponseToJSON(value?: StockResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'payload': StockPayloadToJSON(value.payload),
        'message': value.message,
    };
}


