/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum STOCKTXNACTION {
    ADD = 'ADD',
    WITHDRAW = 'WITHDRAW',
    ORDER = 'ORDER'
}

export function STOCKTXNACTIONFromJSON(json: any): STOCKTXNACTION {
    return STOCKTXNACTIONFromJSONTyped(json, false);
}

export function STOCKTXNACTIONFromJSONTyped(json: any, ignoreDiscriminator: boolean): STOCKTXNACTION {
    return json as STOCKTXNACTION;
}

export function STOCKTXNACTIONToJSON(value?: STOCKTXNACTION | null): any {
    return value as any;
}

