/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TAXTYPE,
    TAXTYPEFromJSON,
    TAXTYPEFromJSONTyped,
    TAXTYPEToJSON,
} from './';

/**
 * 
 * @export
 * @interface TaxonomyReq
 */
export interface TaxonomyReq {
    /**
     * 
     * @type {string}
     * @memberof TaxonomyReq
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof TaxonomyReq
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TaxonomyReq
     */
    titleTh: string;
    /**
     * 
     * @type {TAXTYPE}
     * @memberof TaxonomyReq
     */
    taxType: TAXTYPE;
    /**
     * 
     * @type {boolean}
     * @memberof TaxonomyReq
     */
    isActive: boolean;
    /**
     * 
     * @type {any}
     * @memberof TaxonomyReq
     */
    taxPrimaryImgId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof TaxonomyReq
     */
    taxThumbnailId?: any | null;
}

export function TaxonomyReqFromJSON(json: any): TaxonomyReq {
    return TaxonomyReqFromJSONTyped(json, false);
}

export function TaxonomyReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxonomyReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'titleTh': json['title_th'],
        'taxType': TAXTYPEFromJSON(json['tax_type']),
        'isActive': json['isActive'],
        'taxPrimaryImgId': !exists(json, 'TaxPrimaryImgId') ? undefined : json['TaxPrimaryImgId'],
        'taxThumbnailId': !exists(json, 'TaxThumbnailId') ? undefined : json['TaxThumbnailId'],
    };
}

export function TaxonomyReqToJSON(value?: TaxonomyReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'id': value.id,
        'title_th': value.titleTh,
        'tax_type': TAXTYPEToJSON(value.taxType),
        'isActive': value.isActive,
        'TaxPrimaryImgId': value.taxPrimaryImgId,
        'TaxThumbnailId': value.taxThumbnailId,
    };
}


