/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaxonomyPayload,
    TaxonomyPayloadFromJSON,
    TaxonomyPayloadFromJSONTyped,
    TaxonomyPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface TaxonomyResponse
 */
export interface TaxonomyResponse {
    /**
     * 
     * @type {boolean}
     * @memberof TaxonomyResponse
     */
    success: boolean;
    /**
     * 
     * @type {TaxonomyPayload}
     * @memberof TaxonomyResponse
     */
    payload?: TaxonomyPayload;
    /**
     * 
     * @type {any}
     * @memberof TaxonomyResponse
     */
    message?: any | null;
}

export function TaxonomyResponseFromJSON(json: any): TaxonomyResponse {
    return TaxonomyResponseFromJSONTyped(json, false);
}

export function TaxonomyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxonomyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'payload': !exists(json, 'payload') ? undefined : TaxonomyPayloadFromJSON(json['payload']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function TaxonomyResponseToJSON(value?: TaxonomyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'payload': TaxonomyPayloadToJSON(value.payload),
        'message': value.message,
    };
}


