/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TAXTYPE {
    CATEGORY = 'CATEGORY',
    TAG = 'TAG',
    COLOR = 'COLOR',
    COLLECTION = 'COLLECTION',
    BRAND = 'BRAND'
}

export function TAXTYPEFromJSON(json: any): TAXTYPE {
    return TAXTYPEFromJSONTyped(json, false);
}

export function TAXTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): TAXTYPE {
    return json as TAXTYPE;
}

export function TAXTYPEToJSON(value?: TAXTYPE | null): any {
    return value as any;
}

