/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IStock,
    IStockFromJSON,
    IStockFromJSONTyped,
    IStockToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateStocksArr
 */
export interface UpdateStocksArr {
    /**
     * 
     * @type {number}
     * @memberof UpdateStocksArr
     */
    stockId: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateStocksArr
     */
    quantity: number;
    /**
     * 
     * @type {IStock}
     * @memberof UpdateStocksArr
     */
    currentStock?: IStock;
}

export function UpdateStocksArrFromJSON(json: any): UpdateStocksArr {
    return UpdateStocksArrFromJSONTyped(json, false);
}

export function UpdateStocksArrFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStocksArr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stockId': json['stockId'],
        'quantity': json['quantity'],
        'currentStock': !exists(json, 'currentStock') ? undefined : IStockFromJSON(json['currentStock']),
    };
}

export function UpdateStocksArrToJSON(value?: UpdateStocksArr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stockId': value.stockId,
        'quantity': value.quantity,
        'currentStock': IStockToJSON(value.currentStock),
    };
}


