/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IAddress,
    IAddressFromJSON,
    IAddressFromJSONTyped,
    IAddressToJSON,
    IBodyProportion,
    IBodyProportionFromJSON,
    IBodyProportionFromJSONTyped,
    IBodyProportionToJSON,
    IMember,
    IMemberFromJSON,
    IMemberFromJSONTyped,
    IMemberToJSON,
    IUserSettings,
    IUserSettingsFromJSON,
    IUserSettingsFromJSONTyped,
    IUserSettingsToJSON,
    USERTYPE,
    USERTYPEFromJSON,
    USERTYPEFromJSONTyped,
    USERTYPEToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserUpdateReq
 */
export interface UserUpdateReq {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateReq
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateReq
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateReq
     */
    nickName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateReq
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateReq
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateReq
     */
    contactNum?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateReq
     */
    dob?: string;
    /**
     * 
     * @type {Array<IAddress>}
     * @memberof UserUpdateReq
     */
    addresses?: Array<IAddress>;
    /**
     * 
     * @type {IUserSettings}
     * @memberof UserUpdateReq
     */
    settings?: IUserSettings;
    /**
     * 
     * @type {IBodyProportion}
     * @memberof UserUpdateReq
     */
    bodyProportion?: IBodyProportion;
    /**
     * 
     * @type {USERTYPE}
     * @memberof UserUpdateReq
     */
    userType?: USERTYPE;
    /**
     * 
     * @type {IMember}
     * @memberof UserUpdateReq
     */
    member?: IMember;
    /**
     * 
     * @type {number}
     * @memberof UserUpdateReq
     */
    defaultCurrency?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UserUpdateReq
     */
    active?: boolean;
}

export function UserUpdateReqFromJSON(json: any): UserUpdateReq {
    return UserUpdateReqFromJSONTyped(json, false);
}

export function UserUpdateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'nickName': !exists(json, 'nickName') ? undefined : json['nickName'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'contactNum': !exists(json, 'contactNum') ? undefined : json['contactNum'],
        'dob': !exists(json, 'dob') ? undefined : json['dob'],
        'addresses': !exists(json, 'addresses') ? undefined : ((json['addresses'] as Array<any>).map(IAddressFromJSON)),
        'settings': !exists(json, 'settings') ? undefined : IUserSettingsFromJSON(json['settings']),
        'bodyProportion': !exists(json, 'bodyProportion') ? undefined : IBodyProportionFromJSON(json['bodyProportion']),
        'userType': !exists(json, 'user_type') ? undefined : USERTYPEFromJSON(json['user_type']),
        'member': !exists(json, 'member') ? undefined : IMemberFromJSON(json['member']),
        'defaultCurrency': !exists(json, 'defaultCurrency') ? undefined : json['defaultCurrency'],
        'active': !exists(json, 'active') ? undefined : json['active'],
    };
}

export function UserUpdateReqToJSON(value?: UserUpdateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'nickName': value.nickName,
        'username': value.username,
        'email': value.email,
        'contactNum': value.contactNum,
        'dob': value.dob,
        'addresses': value.addresses === undefined ? undefined : ((value.addresses as Array<any>).map(IAddressToJSON)),
        'settings': IUserSettingsToJSON(value.settings),
        'bodyProportion': IBodyProportionToJSON(value.bodyProportion),
        'user_type': USERTYPEToJSON(value.userType),
        'member': IMemberToJSON(value.member),
        'defaultCurrency': value.defaultCurrency,
        'active': value.active,
    };
}


