/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum USERTYPE {
    ADMIN = 'ADMIN',
    STAFF = 'STAFF',
    CUSTOMER = 'CUSTOMER'
}

export function USERTYPEFromJSON(json: any): USERTYPE {
    return USERTYPEFromJSONTyped(json, false);
}

export function USERTYPEFromJSONTyped(json: any, ignoreDiscriminator: boolean): USERTYPE {
    return json as USERTYPE;
}

export function USERTYPEToJSON(value?: USERTYPE | null): any {
    return value as any;
}

