/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IProduct,
    IProductFromJSON,
    IProductFromJSONTyped,
    IProductToJSON,
} from './';

/**
 * 
 * @export
 * @interface WishListPayload
 */
export interface WishListPayload {
    /**
     * 
     * @type {Array<IProduct>}
     * @memberof WishListPayload
     */
    wishlist?: Array<IProduct>;
}

export function WishListPayloadFromJSON(json: any): WishListPayload {
    return WishListPayloadFromJSONTyped(json, false);
}

export function WishListPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishListPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'wishlist': !exists(json, 'wishlist') ? undefined : ((json['wishlist'] as Array<any>).map(IProductFromJSON)),
    };
}

export function WishListPayloadToJSON(value?: WishListPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wishlist': value.wishlist === undefined ? undefined : ((value.wishlist as Array<any>).map(IProductToJSON)),
    };
}


