/* tslint:disable */
/* eslint-disable */
/**
 * only-bu-BE
 * BE
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    WishListPayload,
    WishListPayloadFromJSON,
    WishListPayloadFromJSONTyped,
    WishListPayloadToJSON,
} from './';

/**
 * 
 * @export
 * @interface WishListResponse
 */
export interface WishListResponse {
    /**
     * 
     * @type {boolean}
     * @memberof WishListResponse
     */
    success: boolean;
    /**
     * 
     * @type {WishListPayload}
     * @memberof WishListResponse
     */
    payload?: WishListPayload;
    /**
     * 
     * @type {any}
     * @memberof WishListResponse
     */
    message?: any | null;
}

export function WishListResponseFromJSON(json: any): WishListResponse {
    return WishListResponseFromJSONTyped(json, false);
}

export function WishListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'payload': !exists(json, 'payload') ? undefined : WishListPayloadFromJSON(json['payload']),
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function WishListResponseToJSON(value?: WishListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'payload': WishListPayloadToJSON(value.payload),
        'message': value.message,
    };
}


